
CREATE TABLE CAR_DETAILS (ID INTEGER not null, MODEL varchar(1000) not null, BRAND varchar(1000) not null, ENGINE_TYPE varchar(20),COLOR varchar(100), NO_OF_SEATS INTEGER not null,TANK_SIZE varchar(10) not null, MILEAGE varchar(10) not null, PRICE varchar(100) not null, primary key (ID));

INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (1, 'TIAGO', 'TATA', 'PETROL', 'RED', 5, '60', '19', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (2, 'NEXON', 'TATA', 'DIESEL', 'BLUE', 5, '65', '20', '1200000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (3, 'PUNCH', 'TATA', 'PETROL', 'WHITE', 5, '60', '18', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (4, 'ALTROZ', 'TATA', 'PETROL', 'BLACK', 5, '63', '19', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (5, 'NANO', 'TATA', 'PETROL', 'SILVER', 5, '20', '22', '300000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (6, 'TIAGO', 'TATA', 'PETROL', 'WHITE', 5, '60', '19', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (7, 'NEXON', 'TATA', 'PETROL', 'RED', 5, '65', '19', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (8, 'PUNCH', 'TATA', 'DIESEL', 'RED', 5, '60', '19', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (9, 'ALTROZ', 'TATA', 'DIESEL', 'WHITE', 5, '60', '23', '900000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (10, 'NANO', 'TATA', 'PETROL', 'RED', 4, '20', '19', '300000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (11, 'TIGOR', 'TATA', 'PETROL', 'BLACK', 5, '65', '19', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (12, 'HARRIER', 'TATA', 'DIESEL', 'SILVER', 7, '7', '16', '2000000');

INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (13, 'CRETA', 'HYUNDAI', 'PETROL', 'RED', 5, '50', '20', '1500000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (14, 'VERNA', 'HYUNDAI', 'PETROL', 'WHITE', 5, '55', '19', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (15, 'CRETA', 'HYUNDAI', 'DIESEL', 'BLACK', 5, '50', '22', '1400000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (16, 'VERNA', 'HYUNDAI', 'DIESEL', 'BLUE', 5, '55', '23', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (17, 'I20', 'HYUNDAI', 'PETROL', 'RED', 5, '37', '19', '900000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (18, 'I10', 'HYUNDAI', 'PETROL', 'GOLDEN', 5, '30', '22', '700000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (19, 'CENTRO', 'HYUNDAI', 'PETROL', 'RED', 5, '40', '19', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (20, 'VENUE', 'HYUNDAI', 'PETROL', 'WHITE', 5, '45', '17', '1000000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (21, 'VENUE', 'HYUNDAI', 'PETROL', 'BLUE', 5, '45', '23', '1000000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (22, 'EXTER', 'HYUNDAI', 'PETROL', 'RED', 5, '40', '19', '700000');

INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (23, 'PUNCH', 'TATA', 'PETROL', 'RED', 5, '60', '18', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (24, 'PUNCH', 'TATA', 'PETROL', 'BLACK', 5, '60', '19', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (25, 'NEXON', 'TATA', 'PETROL', 'GOLDEN', 5, '65', '19', '800000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (26, 'NEXON', 'TATA', 'PETROL', 'RED', 5, '65', '19', '900000');
INSERT INTO CAR_DETAILS (ID,MODEL,BRAND,ENGINE_TYPE,COLOR,NO_OF_SEATS,TANK_SIZE,MILEAGE,PRICE) VALUES (27, 'TIGOR', 'TATA', 'PETROL', 'WHITE', 5, '64', '20', '900000');





